### ISSUE TITLE
Can we embed this library in our own UI and using flutter camera instead of native camera?

### ISSUE THREAD

**Issue by filiocorp** [criistian14/flutter_document_scanner#12]
This is a general question and I was not sure where to ask it. 

Is it possible to use this library inside our own UI and customizable flutter camera? This means that the process of taking picture will be done using the host app and this library will be used as an engine to do document scanning.

**Comment by criistian14** [comment]
Hi @filiocorp,

Exactly, I created this library with that in mind, so it can be fully customizable in terms of UI. It uses the Flutter [camera library](https://pub.dev/packages/camera), but if you prefer, you can use image_picker or any other method to pass the image and manage the document. Additionally, you can customize each page of the process ([taking, cropping, and editing](https://github.com/criistian14/flutter_document_scanner/blob/master/flutter_document_scanner/example/lib/pages/custom_page.dart)). Each page is a Stack, and with the children property, you can pass widgets and use [controller](https://github.com/criistian14/flutter_document_scanner/tree/master/flutter_document_scanner#actions) to achieve the desired customization.


If you want, you can see an example using image_picker here: [Example using Image Picker](https://github.com/criistian14/flutter_document_scanner/blob/master/flutter_document_scanner/example/lib/pages/from_gallery_page.dart).

**Comment by criistian14** [comment]
As there are no further questions regarding this topic, I will go ahead and close the issue. If you have any more questions or need further assistance in the future, please feel free to open a new issue.
