### ISSUE TITLE
select image from gallery

### ISSUE THREAD

**Issue by faslurrajah** [criistian14/flutter_document_scanner#2]
select the image from the gallery possible?

**Comment by criistian14** [comment]
The findContoursFromExternalImage() functionality is added to the controller to find the contours of an image that can be passed from the internet, gallery or other non-camera sources.

For more information on the implementation you can use the [from_gallery_page.dart](https://github.com/criistian14/flutter_document_scanner/blob/fe82588eb3f42e817ab02c20a4027296bef6da6b/flutter_document_scanner/example/lib/pages/from_gallery_page.dart) example page.
