### ISSUE TITLE
Not running example and plugin in another project

### ISSUE THREAD

**Issue by Andreylk4774** [criistian14/flutter_document_scanner#4]
Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `document_edge` from `.symlinks/plugins/document_edge/ios`
    [!] Failed to load 'document_edge' podspec: 
    [!] Invalid `document_edge.podspec` file: syntax error, unexpected **arg
      s.source_files = Classes/**/*.{swift,c,m,h,mm,cpp,plist}
                                                 ^~

<img width="635" alt="Снимок экрана 2022-10-18 в 10 55 08" src="https://user-images.githubusercontent.com/19721726/196370667-d7d1342e-0601-42f4-a89e-b161ec606c3e.png">

**Comment by criistian14** [comment]
It was because it was not yet implemented for iOS.

Currently since version 1.1.0 is already implemented and working for iOS.


https://github.com/criistian14/flutter_document_scanner/assets/31596756/8a61ed16-02c1-4fba-b65f-9356ef035226
